USE transcaribe;

-- Insertar las líneas del metro
INSERT INTO `RUTAS` (name) VALUES
("PORTAL-CENTRO"),
("PORTAL2-CENTRO2"),
("PORTAL-CRESPO"),
("PORTAL-BOCAGRANDE"),
("CAMPANOS-13 DE JUNIO-CENTRO"),
("PORTAL-BOSQUE-CENTRO"),
("PORTAL-CONSULADO-CENTRO"),
("T.DE TRANSPORTE-AV. PEDRO R-CENTRO"),
("CIUDAD 2000-C/LUQUE-BOCAGRANDE"),
("VARIANTE-CENTRO");


INSERT INTO `VEHICULO` (serial_number, line_id, type) VALUES
('T100E', 1, 1),
('T101', 2, 1),
('T102', 3, 1),
('T103', 4, 1),
('X101', 5, 2),
('X102', 6, 2),
('X103', 7, 2),
('X104', 8, 2),
('X105', 9, 2),
('X106', 10, 2);

INSERT INTO `ESTACIONES` (name) VALUES
('PATIO PORTAL'),
('MADRE BERNARDA'),
('LA CASTELLANA'),
('LOS ANGELES'),
('LOS EJECUTIVOS'),
('VILLA OLIMPICA'),
('CUATRO VIENTOS'),
('REPUBLICA DEL LIBANO'),
('ESPAÑA'),
('MARIA AUX'),
('EL PRADO'),
('BAZURTO'),
('DELICIAS'),
('LA POPA'),
('LO AMADOR'),
('CHAMBACU'),
('CENTRO'),
('LA BODEGUITA');