USE transcaribe;

DROP TABLE`rutas_estaciones`;
INSERT INTO `rutas_estaciones` (rutas_id, estaciones_id) VALUES
(
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='PATIO PORTAL')    
), 
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MADRE BERNARDA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA CASTELLANA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CUATRO VIENTOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MARIA AUX')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL-CENTRO'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- PORTAL2-CENTRO2 T101
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MADRE BERNARDA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA CASTELLANA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LOS EJECUTIVOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CUATRO VIENTOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='ESPAÑA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='EL PRADO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA POPA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CHAMBACU')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`='PORTAL2-CENTRO2'),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- PORTAL-CRESPO T102
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='PATIO PORTAL')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MADRE BERNARDA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LOS ANGELES')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='VILLA OLIMPICA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='REPUBLICA DEL LIBANO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MARIA AUX')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='EL PRADO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CHAMBACU')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CRESPO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
-- PORTAL-BOCAGRANDE T103
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='PATIO PORTAL')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MADRE BERNARDA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA CASTELLANA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LOS EJECUTIVOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CUATRO VIENTOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='ESPAÑA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA POPA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CHAMBACU')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- CAMPANOS-13-DE JUNIO-CENTRO X101
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LOS EJECUTIVOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='VILLA OLIMPICA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CUATRO VIENTOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='REPUBLICA DEL LIBANO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='ESPAÑA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MARIA AUX')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CHAMBACU')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CAMPANOS-13 DE JUNIO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- PORTAL-BOSQUE-CENTRO X102
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='PATIO PORTAL')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MADRE BERNARDA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='DELICIAS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LO AMADOR')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-BOSQUE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- PORTAL-CONSULADO-CENTRO X103
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='PATIO PORTAL')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MADRE BERNARDA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='EL PRADO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='DELICIAS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="PORTAL-CONSULADO-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- T.DE TRANSPORTE-AV. PEDRO R-CENTRO X104
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="T.DE TRANSPORTE-AV. PEDRO R-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="T.DE TRANSPORTE-AV. PEDRO R-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA POPA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="T.DE TRANSPORTE-AV. PEDRO R-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CHAMBACU')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="T.DE TRANSPORTE-AV. PEDRO R-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="T.DE TRANSPORTE-AV. PEDRO R-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- CIUDAD 2000-C/LUQUE-BOCAGRANDE X105
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CIUDAD 2000-C/LUQUE-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='BAZURTO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CIUDAD 2000-C/LUQUE-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='DELICIAS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CIUDAD 2000-C/LUQUE-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LO AMADOR')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CIUDAD 2000-C/LUQUE-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="CIUDAD 2000-C/LUQUE-BOCAGRANDE"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
),
-- VARIANTE-CENTRO X106
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA CASTELLANA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LOS EJECUTIVOS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='REPUBLICA DEL LIBANO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='MARIA AUX')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='DELICIAS')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA POPA')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LO AMADOR')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
   (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='CENTRO')
),
  (
   (SELECT `RUTAS`.`id` FROM `RUTAS` WHERE `RUTAS`.`name`="VARIANTE-CENTRO"),
   (SELECT `ESTACIONES`.`id` FROM `ESTACIONES` WHERE `ESTACIONES`.`name`='LA BODEGUITA')
);